### ISSUE TITLE
Sample Value selection ignored in builder workflow

### ISSUE THREAD

**Issue by sfc-gh-jsummer** [Snowflake-Labs/semantic-model-generator#117]
Entered 3 for sample values in builder workflow and received 20+ for many dimensions.

`      - name: SALESORDERNUMBER
        synonyms:
          - '  ' # <FILL-OUT>
        description: Unique identifier for each sales order.__ # <AUTO-GENERATED DESCRIPTION, PLEASE MODIFY AND REMOVE THE __ AT THE END>
        expr: SALESORDERNUMBER
        data_type: TEXT
        sample_values:
          - SO43700
          - SO43699
          - SO43698
          - SO43697
          - SO43701
          - SO43702
          - SO43705
          - SO43703
          - SO43707
          - SO43708
          - SO43710
          - SO43709
          - SO43711
          - SO43712
          - SO43713
          - SO43719
          - SO43718
          - SO43720
          - SO43721
          - SO43723
          - SO43724
          - SO43726
          - SO43725
          - SO43715
          - SO43716`

**Comment by sfc-gh-cnivera** [comment]
Ah I think this is mainly a gap in the copy -- the sample values setting is mainly a maximum defined for columns. For dimensions, time measures, and measures, we hardcode a minimum of 25, 3, and 3 respectively. 

I'll update the description in the tooltip to reflect this!
