### ISSUE TITLE
provide validation for LLM context window exceeding in the generated model. 

### ISSUE THREAD

**Issue by Sangamesh-ts** [Snowflake-Labs/semantic-model-generator#134]
Exception: Failed request with status 400: {'status': 400, 'content': '{\n\t"message":\t"The semantic model you provided is too large, surpassing the LLM context window. Please reduce the size of your semantic model.",\n\t"code":\tnull,\n\t"error_code":\t"392701",\n\t"request_id":\t"6"\n}', 'headers': {'\nDate': 'Thu, 15 Aug 2024 22:53:51 GMT', '\nTransfer-Encoding': 'chunked', '\nContent-Type': 'application/json'}}

**Comment by sfc-gh-cnivera** [comment]
Believe our new context length validation should cover this - closing for now.
