### ISSUE TITLE
Initial Generated Yaml file should not need extra editing to be valid

### ISSUE THREAD

**Issue by sfc-gh-rblum** [Snowflake-Labs/semantic-model-generator#142]
Remove comments and the empty expression value for Filters section

**Comment by sfc-gh-cnivera** [comment]
I think this discussion pre-dates when I started working on the OSS stuff, but IIUC we went back and forth between having the model be valid out of the box vs exposing these extra fields and having the customer fill them out. 

@sfc-gh-rehuang probably has the most context on this, so we should discuss with her when she's back.
