### ISSUE TITLE
AttributeError: module 'streamlit' has no attribute 'dialog'

### ISSUE THREAD

**Issue by rrprasan** [Snowflake-Labs/semantic-model-generator#162]
I am getting this error when I run `make run_admin_app`

**Comment by sfc-gh-cnivera** [comment]
Hi @rrprasan , could you please verify that you have a Streamlit version `^1.37.1`? I believe `st.dialog` was added to the standard Streamlit library in a more recent update.

**Comment by rrprasan** [comment]
Yes, upgrading Streamlit to 1.37.1 worked. Thank you @sfc-gh-cnivera. I am grateful for your time!

**Comment by rrprasan** [comment]
Issue fixed by @sfc-gh-cnivera
