### ISSUE TITLE
Local Streamlit deployment readme has dead link

### ISSUE THREAD

**Issue by MartinCampbellS4RB** [Snowflake-Labs/semantic-model-generator#199]
In the readme instructions for a local deployment of Streamlit, after configuring your connection, you are directed by a hyperlink to 

> continue to [Start Local Streamlit App](https://github.com/Snowflake-Labs/semantic-model-generator/blob/main/start-local-streamlit-app) once completed.

However, the URL - https://github.com/Snowflake-Labs/semantic-model-generator/blob/main/start-local-streamlit-app - takes you to a page that does not exist and returns a 404 error
![image](https://github.com/user-attachments/assets/ae963ba9-d1e8-4ffa-9290-19062247e85a)

**Comment by sfc-gh-cnivera** [comment]
Thanks! Fixed.
