### ISSUE TITLE
When install with whl file and error occurred.

### ISSUE THREAD

**Issue by enowy** [Snowflake-Labs/semantic-model-generator#65]
When you run "pip install dist/*.whl" in the first step of README's Usage > Generation - Python, a build error in pyarrow occurs.

> Using cached rpds_py-0.18.1-cp312-cp312-macosx_10_12_x86_64.whl (329 kB)
> Using cached smmap-5.0.1-py3-none-any.whl (24 kB)
> Building wheels for collected packages: pyarrow
>   Building wheel for pyarrow (pyproject.toml) ... error
>   error: subprocess-exited-with-error
>   
>   × Building wheel for pyarrow (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> [324 lines of output]
>       <string>:36: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
>       WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'
>       Traceback (most recent call last):
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>           ArrowConfig.cmake
>           arrow-config.cmake
>       
>         Add the installation prefix of "Arrow" to CMAKE_PREFIX_PATH or set
>         "Arrow_DIR" to a directory containing one of the above files.  If "Arrow"
>         provides a separate development package or SDK, be sure it has been
>         installed.
>       
>       
>       -- Configuring incomplete, errors occurred!
>       error: command '/usr/local/bin/cmake' failed with exit code 1
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for pyarrow
> Failed to build pyarrow
> ERROR: Could not build wheels for pyarrow, which is required to install pyproject.toml-based projects

**Comment by sfc-gh-cnivera** [comment]
We are phasing out `*.whl` support, so closing this issue.
