### ISSUE TITLE
Streamlit App: Merge and Clean Env Vars/UI Entry

### ISSUE THREAD

**Issue by sfc-gh-jsummer** [Snowflake-Labs/semantic-model-generator#92]
Clean up and unify required env variables for Streamlit app. Right now, they have to be set as env variables and UI entry seems to be largely ignored.

**Comment by sfc-gh-cnivera** [comment]
Removed the UI options for now since it was a bit misleading, and it's better to just have one source of truth (I don't see these values changing frequently anyway, so the value of a UI affordance is not high IMO)

Happy to revisit this!
