### ISSUE TITLE
Drop down for DB, Schema, stage , yaml

### ISSUE THREAD

**Issue by sfc-gh-rblum** [Snowflake-Labs/semantic-model-generator#94]
It would fairly be easy to create a drop down list for DB, Schema and stage in the streamlit app so it doesn't have to be hand typed, and this could be done once logged into app.

**Comment by sfc-gh-rblum** [comment]
Sample code for database, schema, table, stage and yaml file dropdowns:

`    # Show databases and create a select box for the database selection
    databases_df = session.sql("SHOW DATABASES").collect()
    databases = [row['name'] for row in databases_df]
    database_selector = st.selectbox("Select Database", databases)

    # Show schemas based on the selected database and create a select box for schema selection
    schemas_df = session.sql(f"SHOW SCHEMAS IN DATABASE {database_selector}").collect()
    schemas = [row['name'] for row in schemas_df]
    schema_selector = st.selectbox("Select Schema", schemas)

    # Show tables based on the selected schema and create a select box for table selection
    tables_df = session.sql(f"SHOW TABLES IN {database_selector}.{schema_selector}").collect()
    tables = [row['name'] for row in tables_df]
    table_selector = st.selectbox("Select Table", tables)

    
    # Show stages based on the selected schema and create a select box for table selection
    stages_df = session.sql(f"SHOW STAGES IN {database_selector}.{schema_selector}").collect()
    stages = [row['name'] for row in stages_df]
    stage_selector = st.selectbox("Select Stage", stages)


    # Show YAML files based on selected stage
    yaml_df = session.sql(f"ls @{database_selector}.{schema_selector}.{stage_selector} pattern = '.*.yaml*'").collect()
    yaml = [row['name'] for row in yaml_df]
    yaml_selector = st.selectbox("Select Yaml", yaml)`

**Comment by sfc-gh-cnivera** [comment]
Commenting on this myself for tracking; I've added a table selector dropdown to the builder flow, but it currently works by running `SHOW TABLES;`. This query can timeout / fail if the user has over 10k tables, so it'd also be better to refactor the builder table selection to use the same db/schema/tables dropdown in order to limit the search space of available tables.
